# Generated by Django 5.2.1 on 2025-05-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@default.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
